sudo: false
language: node_js
node_js:
  - 6

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=firefox BVER=stable

matrix:
  fast_finish: true

before_script:
  - ./node_modules/travis-multirunner/setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

notifications:
  email:
    - aiham@aiham.net
