sudo: false
language: node_js
node_js:
  - 6

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: ./node_modules/.bin/run-tests

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=firefox BVER=stable
  global:
    - TRAVIS=true
    - UNIT_CMD='npm run travis-test'

matrix:
  fast_finish: true

notifications:
  email:
    - aiham@aiham.net
